version: '3.4'
services:
  oracle-server:
    image: oracle-server:${CIRCLE_SHA1}
    volumes:
      - oracle-config:/config
      - oracle-secrets:/key
  oracle-db:
    volumes:
      - db-certs:/certs
  dev:
    build:
      context: .
      target: dev
    image: oracle-dev:${CIRCLE_SHA1}
    volumes:
      - oracle-secrets:/key
      - reports:/reports

  dockerize:
    image: jwilder/dockerize


volumes:
  oracle-db-data:
  oracle-config:
    external: true
  oracle-secrets:
    external: true
  db-certs:
    external: true
  reports:
    external: true
